// Generated by CoffeeScript 1.6.1
(function() {
  var get_time_range, initialize_projects, insert_companies, insert_dates, start_timeline;

  $(document).ready(function() {
    start_timeline();
    return $(window).resize(start_timeline);
  });

  start_timeline = function() {
    $("#projects").empty();
    $("#timeline").empty();
    return $.getJSON("data.json", function(data) {
      var years;
      years = get_time_range(data);
      console.log(years);
      insert_dates(years);
      insert_companies(data["companies"]);
      return $(data["companies"]).each(initialize_projects);
    });
  };

  get_time_range = function(data) {
    var max, min, _i, _results;
    min = Math.min.apply(Math, data["companies"].map(function(company) {
      return company["from"]["year"];
    }));
    max = Math.max.apply(Math, data["companies"].map(function(company) {
      return company["to"]["year"];
    }));
    return (function() {
      _results = [];
      for (var _i = min; min <= max ? _i <= max : _i >= max; min <= max ? _i++ : _i--){ _results.push(_i); }
      return _results;
    }).apply(this);
  };

  insert_dates = function(years) {
    var year, _i, _len, _results;
    $("#timeline").append("<div class='dates'></div>");
    $("#timeline > .dates").append("<div class='dates-row'></div>");
    _results = [];
    for (_i = 0, _len = years.length; _i < _len; _i++) {
      year = years[_i];
      _results.push($("#timeline > .dates > .dates-row").append("<div class='date'>" + year + "</div>"));
    }
    return _results;
  };

  insert_companies = function(companies) {
    var first_year, first_year_div, last_year, month_width;
    $("#timeline").append("<div class='companies'></div>");
    first_year_div = $("#timeline > .dates > .dates-row > .date").first();
    month_width = first_year_div.outerWidth() / 12;
    first_year = parseInt(first_year_div.text());
    last_year = parseInt($("#timeline > .dates > .dates-row > .date").last().text());
    return $(companies).each(function(i, company) {
      var left_offset, month, right_offset, year;
      year = company["from"]["year"];
      month = company["from"]["month"];
      left_offset = ((year - first_year) * 12 + month - 1) * month_width;
      year = company["to"]["year"];
      month = company["to"]["month"];
      console.log(last_year - year);
      right_offset = ((last_year - year) * 12 + (12 - month + 1)) * month_width;
      companies = $("#timeline > .companies").append("<div      class='company'      data-company='company_" + i + "'      style='        left: " + left_offset + "px;        right: " + right_offset + "px;      '>" + company["name"] + "</div>");
      $("#timeline > .companies > .company").last().mouseover(function() {
        $("#projects > .company_projects").fadeOut(500);
        return $("#projects > #company_" + i + ".company_projects").delay(500).fadeIn(500);
      });
      return companies.append("<div class='company_info'>      <span class='title'>" + company["title"] + "</span>      <span class='desc'>" + company["desc"] + "</span></div>");
    });
  };

  initialize_projects = function(i, company) {
    var project, _i, _len, _ref, _results;
    $('#projects').append("<div class='company_projects' id='company_" + i + "'><h1>Projects</h1></div>");
    _ref = company["projects"];
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      project = _ref[_i];
      _results.push($('#projects > .company_projects').last().append("<div class='project'>       <h2>" + project["name"] + "</h2>       <p>" + project["desc"] + "</p>      </div>"));
    }
    return _results;
  };

}).call(this);
